---
- apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'

- include: manager_apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: manager_yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: Clone SimpleSAMLphp from GitHub
  git:
    repo: "{{ simplesamlphp_repo }}"
    dest: "{{ simplesamlphp_dir }}"
    version: "{{ simplesamlphp_branch }}"

- shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: "{{ simplesamlphp_dir }}"
    creates: "{{ simplesamlphp_dir }}/composer.phar"

- command: php composer.phar install
  args:
    chdir: "{{ simplesamlphp_dir }}"
    creates: "{{ simplesamlphp_dir }}/vendor"

- include: vhost.yml
