---
- apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'

- include: manager_apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: manager_yum.yml
  when: ansible_pkg_mgr == 'yum'
